# Copyright (c) 2024, NVIDIA CORPORATION.

repos:
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: verify-copyright
  - repo: https://github.com/rapidsai/dependency-file-generator
    rev: v1.14.0
    hooks:
      - id: rapids-dependency-file-generator
        args: ["--clean"]

default_language_version:
  python: python3
